# Consumindo API de dados de países

Fonte: https://restcountries.com/

## O que é uma API RESTful?

Uma API RESTful é uma API que segue o padrão REST (Representational State Transfer). Esse padrão é baseado em 6 princípios:

- **Cliente-servidor**: o cliente e o servidor são entidades independentes e cada um deles pode ser substituído, desde que a interface entre eles seja mantida.
- **Stateless**: cada requisição do cliente para o servidor deve conter todas as informações necessárias para o servidor entender a requisição, sem guardar nenhum tipo de informação de requisições anteriores. Isso significa que nenhuma informação de estado é mantida entre requisições.
- **Cache**: o cliente pode fazer requisições de cache para o servidor. O servidor deve informar se as requisições podem ser cacheadas ou não.
- **Interface uniforme**: a interface entre o cliente e o servidor deve ser uniforme para todas as requisições. Isso significa que o protocolo HTTP deve ser seguido, utilizando os verbos HTTP corretos (GET, POST, PUT, DELETE, etc).
- **Sistema em camadas**: o cliente acessa o servidor através de camadas intermediárias, como um proxy. Essas camadas intermediárias podem oferecer serviços como cache, load balancing, segurança, etc.
- **Código sob demanda (opcional)**: o servidor pode estender a funcionalidade do cliente enviando código para ser executado no cliente. Isso é opcional e não é muito utilizado.

Fonte: https://www.redhat.com/pt-br/topics/api/what-is-a-rest-api

## Endpoint all

In [9]:
import requests

URL_ALL = "https://restcountries.com/v3.1/all"

resposta = requests.get(URL_ALL)
resposta.status_code

400

In [10]:
resposta.headers

{'Server': 'nginx/1.22.1', 'Date': 'Fri, 17 Apr 2026 17:41:35 GMT', 'Content-Type': 'application/json', 'Content-Length': '96', 'Connection': 'keep-alive'}

In [11]:
resposta.json()[:5]

KeyError: slice(None, 5, None)

In [ ]:
resposta_all = resposta.json()
resposta_all[0]

{'name': {'common': 'Saudi Arabia',
  'official': 'Kingdom of Saudi Arabia',
  'nativeName': {'ara': {'official': 'المملكة العربية السعودية',
    'common': 'العربية السعودية'}}},
 'tld': ['.sa', '.السعودية'],
 'cca2': 'SA',
 'ccn3': '682',
 'cca3': 'SAU',
 'cioc': 'KSA',
 'independent': True,
 'status': 'officially-assigned',
 'unMember': True,
 'currencies': {'SAR': {'name': 'Saudi riyal', 'symbol': 'ر.س'}},
 'idd': {'root': '+9', 'suffixes': ['66']},
 'capital': ['Riyadh'],
 'altSpellings': ['Saudi',
  'SA',
  'Kingdom of Saudi Arabia',
  'Al-Mamlakah al-‘Arabiyyah as-Su‘ūdiyyah'],
 'region': 'Asia',
 'subregion': 'Western Asia',
 'languages': {'ara': 'Arabic'},
 'translations': {'ara': {'official': 'المملكة العربية السعودية',
   'common': 'السعودية'},
  'bre': {'official': 'Rouantelezh Arabia Saoudat',
   'common': 'Arabia Saoudat'},
  'ces': {'official': 'Saúdskoarabské království', 'common': 'Saúdská Arábie'},
  'cym': {'official': 'Kingdom of Saudi Arabia', 'common': 'Saudi Arabia'},
  'deu': {'official': 'Königreich Saudi-Arabien', 'common': 'Saudi-Arabien'},
  'est': {'official': 'Saudi Araabia Kuningriik', 'common': 'Saudi Araabia'},
  'fin': {'official': 'Saudi-Arabian kuningaskunta', 'common': 'Saudi-Arabia'},
  'fra': {'official': "Royaume d'Arabie Saoudite",
   'common': 'Arabie Saoudite'},
  'hrv': {'official': 'Kraljevina Saudijska Arabija',
   'common': 'Saudijska Arabija'},
  'hun': {'official': 'Szaúd-Arábia', 'common': 'Szaúd-Arábia'},
  'ita': {'official': 'Arabia Saudita', 'common': 'Arabia Saudita'},
  'jpn': {'official': 'サウジアラビア王国', 'common': 'サウジアラビア'},
  'kor': {'official': '사우디아라비아 왕국', 'common': '사우디아라비아'},
  'nld': {'official': 'Koninkrijk van Saoedi-Arabië',
   'common': 'Saoedi-Arabië'},
  'per': {'official': 'پادشاهی عربی سَعودی', 'common': 'عربستان سعودی'},
  'pol': {'official': 'Królestwo Arabii Saudyjskiej',
   'common': 'Arabia Saudyjska'},
  'por': {'official': 'Reino da Arábia Saudita', 'common': 'Arábia Saudita'},
  'rus': {'official': 'Королевство Саудовская Аравия',
   'common': 'Саудовская Аравия'},
  'slk': {'official': 'Saudskoarabské kráľovstvo', 'common': 'Saudská Arábia'},
  'spa': {'official': 'Reino de Arabia Saudita', 'common': 'Arabia Saudí'},
  'srp': {'official': 'Краљевина Саудијска Арабија',
   'common': 'Саудијска Арабија'},
  'swe': {'official': 'Kungadömet Saudiarabien', 'common': 'Saudiarabien'},
  'tur': {'official': 'Suudi Arabistan Krallığı', 'common': 'Suudi Arabistan'},
  'urd': {'official': 'مملکتِ سعودی عرب', 'common': 'سعودی عرب'},
  'zho': {'official': '沙特阿拉伯王国', 'common': '沙特阿拉伯'}},
 'latlng': [25.0, 45.0],
 'landlocked': False,
 'borders': ['IRQ', 'JOR', 'KWT', 'OMN', 'QAT', 'ARE', 'YEM'],
 'area': 2149690.0,
 'demonyms': {'eng': {'f': 'Saudi Arabian', 'm': 'Saudi Arabian'},
  'fra': {'f': 'Saoudienne', 'm': 'Saoudien'}},
 'flag': '🇸🇦',
 'maps': {'googleMaps': 'https://goo.gl/maps/5PSjvdJ1AyaLFRrG9',
  'openStreetMaps': 'https://www.openstreetmap.org/relation/307584'},
 'population': 34813867,
 'fifa': 'KSA',
 'car': {'signs': ['SA'], 'side': 'right'},
 'timezones': ['UTC+03:00'],
 'continents': ['Asia'],
 'flags': {'png': 'https://flagcdn.com/w320/sa.png',
  'svg': 'https://flagcdn.com/sa.svg',
  'alt': 'The flag of Saudi Arabia has a green field, at the center of which is an Arabic inscription — the Shahada — in white above a white horizontal sabre with its tip pointed to the hoist side of the field.'},
 'coatOfArms': {'png': 'https://mainfacts.com/media/images/coats_of_arms/sa.png',
  'svg': 'https://mainfacts.com/media/images/coats_of_arms/sa.svg'},
 'startOfWeek': 'sunday',
 'capitalInfo': {'latlng': [24.65, 46.7]},
 'postalCode': {'format': '#####', 'regex': '^(\\d{5})$'}}

In [ ]:
resposta_all[0]['name']

{'common': 'Saudi Arabia',
 'official': 'Kingdom of Saudi Arabia',
 'nativeName': {'ara': {'official': 'المملكة العربية السعودية',
   'common': 'العربية السعودية'}}}

In [ ]:
resposta_all[0]['name']['common']

'Saudi Arabia'

In [ ]:
# procurando pelo Brasil
for pais in resposta_all:
    if pais['name']['common'] == 'Brazil':
        brasil = pais
        print(brasil)

{'name': {'common': 'Brazil', 'official': 'Federative Republic of Brazil', 'nativeName': {'por': {'official': 'República Federativa do Brasil', 'common': 'Brasil'}}}, 'tld': ['.br'], 'cca2': 'BR', 'ccn3': '076', 'cca3': 'BRA', 'cioc': 'BRA', 'independent': True, 'status': 'officially-assigned', 'unMember': True, 'currencies': {'BRL': {'name': 'Brazilian real', 'symbol': 'R$'}}, 'idd': {'root': '+5', 'suffixes': ['5']}, 'capital': ['Brasília'], 'altSpellings': ['BR', 'Brasil', 'Federative Republic of Brazil', 'República Federativa do Brasil'], 'region': 'Americas', 'subregion': 'South America', 'languages': {'por': 'Portuguese'}, 'translations': {'ara': {'official': 'جمهورية البرازيل الاتحادية', 'common': 'البرازيل'}, 'bre': {'official': 'Republik Kevreel Brazil', 'common': 'Brazil'}, 'ces': {'official': 'Brazilská federativní republika', 'common': 'Brazílie'}, 'cym': {'official': 'Gweriniaeth Ffederal Brasil', 'common': 'Brasil'}, 'deu': {'official': 'Föderative Republik Brasilien', 'common': 'Brasilien'}, 'est': {'official': 'Brasiilia Liitvabariik', 'common': 'Brasiilia'}, 'fin': {'official': 'Brasilian liittotasavalta', 'common': 'Brasilia'}, 'fra': {'official': 'République fédérative du Brésil', 'common': 'Brésil'}, 'hrv': {'official': 'Savezne Republike Brazil', 'common': 'Brazil'}, 'hun': {'official': 'Brazil Szövetségi Köztársaság', 'common': 'Brazília'}, 'ita': {'official': 'Repubblica federativa del Brasile', 'common': 'Brasile'}, 'jpn': {'official': 'ブラジル連邦共和国', 'common': 'ブラジル'}, 'kor': {'official': '브라질 연방 공화국', 'common': '브라질'}, 'nld': {'official': 'Federale Republiek Brazilië', 'common': 'Brazilië'}, 'per': {'official': 'جمهوری فدراتیو برزیل', 'common': 'برزیل'}, 'pol': {'official': 'Federacyjna Republika Brazylii', 'common': 'Brazylia'}, 'por': {'official': 'República Federativa do Brasil', 'common': 'Brasil'}, 'rus': {'official': 'Федеративная Республика Бразилия', 'common': 'Бразилия'}, 'slk': {'official': 'Brazílska federatívna republika', 'common': 'Brazília'}, 'spa': {'official': 'República Federativa del Brasil', 'common': 'Brasil'}, 'srp': {'official': 'Савезна Република Бразил', 'common': 'Бразил'}, 'swe': {'official': 'Förbundsrepubliken Brasilien', 'common': 'Brasilien'}, 'tur': {'official': 'Brezilya Federal Cumhuriyeti', 'common': 'Brezilya'}, 'urd': {'official': 'وفاقی جمہوریہ برازیل', 'common': 'برازیل'}, 'zho': {'official': '巴西联邦共和国', 'common': '巴西'}}, 'latlng': [-10.0, -55.0], 'landlocked': False, 'borders': ['ARG', 'BOL', 'COL', 'GUF', 'GUY', 'PRY', 'PER', 'SUR', 'URY', 'VEN'], 'area': 8515767.0, 'demonyms': {'eng': {'f': 'Brazilian', 'm': 'Brazilian'}, 'fra': {'f': 'Brésilienne', 'm': 'Brésilien'}}, 'flag': '🇧🇷', 'maps': {'googleMaps': 'https://goo.gl/maps/waCKk21HeeqFzkNC9', 'openStreetMaps': 'https://www.openstreetmap.org/relation/59470'}, 'population': 212559409, 'gini': {'2019': 53.4}, 'fifa': 'BRA', 'car': {'signs': ['BR'], 'side': 'right'}, 'timezones': ['UTC-05:00', 'UTC-04:00', 'UTC-03:00', 'UTC-02:00'], 'continents': ['South America'], 'flags': {'png': 'https://flagcdn.com/w320/br.png', 'svg': 'https://flagcdn.com/br.svg', 'alt': "The flag of Brazil has a green field with a large yellow rhombus in the center. Within the rhombus is a dark blue globe with twenty-seven small five-pointed white stars depicting a starry sky and a thin white convex horizontal band inscribed with the national motto 'Ordem e Progresso' across its center."}, 'coatOfArms': {'png': 'https://mainfacts.com/media/images/coats_of_arms/br.png', 'svg': 'https://mainfacts.com/media/images/coats_of_arms/br.svg'}, 'startOfWeek': 'monday', 'capitalInfo': {'latlng': [-15.79, -47.88]}, 'postalCode': {'format': '#####-###', 'regex': '^(\\d{8})$'}}

In [ ]:
from pprint import pprint

pprint(brasil)

{'altSpellings': ['BR',
                  'Brasil',
                  'Federative Republic of Brazil',
                  'República Federativa do Brasil'],
 'area': 8515767.0,
 'borders': ['ARG',
             'BOL',
             'COL',
             'GUF',
             'GUY',
             'PRY',
             'PER',
             'SUR',
             'URY',
             'VEN'],
 'capital': ['Brasília'],
 'capitalInfo': {'latlng': [-15.79, -47.88]},
 'car': {'side': 'right', 'signs': ['BR']},
 'cca2': 'BR',
 'cca3': 'BRA',
 'ccn3': '076',
 'cioc': 'BRA',
 'coatOfArms': {'png': 'https://mainfacts.com/media/images/coats_of_arms/br.png',
                'svg': 'https://mainfacts.com/media/images/coats_of_arms/br.svg'},
 'continents': ['South America'],
 'currencies': {'BRL': {'name': 'Brazilian real', 'symbol': 'R$'}},
 'demonyms': {'eng': {'f': 'Brazilian', 'm': 'Brazilian'},
              'fra': {'f': 'Brésilienne', 'm': 'Brésilien'}},
 'fifa': 'BRA',
 'flag': '🇧🇷',
 'flags': {'alt': 'The flag of Brazil has a green field with a large yellow '
                  'rhombus in the center. Within the rhombus is a dark blue '
                  'globe with twenty-seven small five-pointed white stars '
                  'depicting a starry sky and a thin white convex horizontal '
                  "band inscribed with the national motto 'Ordem e Progresso' "
                  'across its center.',
           'png': 'https://flagcdn.com/w320/br.png',
           'svg': 'https://flagcdn.com/br.svg'},
 'gini': {'2019': 53.4},
 'idd': {'root': '+5', 'suffixes': ['5']},
 'independent': True,
 'landlocked': False,
 'languages': {'por': 'Portuguese'},
 'latlng': [-10.0, -55.0],
 'maps': {'googleMaps': 'https://goo.gl/maps/waCKk21HeeqFzkNC9',
          'openStreetMaps': 'https://www.openstreetmap.org/relation/59470'},
 'name': {'common': 'Brazil',
          'nativeName': {'por': {'common': 'Brasil',
                                 'official': 'República Federativa do Brasil'}},
          'official': 'Federative Republic of Brazil'},
 'population': 212559409,
 'postalCode': {'format': '#####-###', 'regex': '^(\\d{8})$'},
 'region': 'Americas',
 'startOfWeek': 'monday',
 'status': 'officially-assigned',
 'subregion': 'South America',
 'timezones': ['UTC-05:00', 'UTC-04:00', 'UTC-03:00', 'UTC-02:00'],
 'tld': ['.br'],
 'translations': {'ara': {'common': 'البرازيل',
                          'official': 'جمهورية البرازيل الاتحادية'},
                  'bre': {'common': 'Brazil',
                          'official': 'Republik Kevreel Brazil'},
                  'ces': {'common': 'Brazílie',
                          'official': 'Brazilská federativní republika'},
                  'cym': {'common': 'Brasil',
                          'official': 'Gweriniaeth Ffederal Brasil'},
                  'deu': {'common': 'Brasilien',
                          'official': 'Föderative Republik Brasilien'},
                  'est': {'common': 'Brasiilia',
                          'official': 'Brasiilia Liitvabariik'},
                  'fin': {'common': 'Brasilia',
                          'official': 'Brasilian liittotasavalta'},
                  'fra': {'common': 'Brésil',
                          'official': 'République fédérative du Brésil'},
                  'hrv': {'common': 'Brazil',
                          'official': 'Savezne Republike Brazil'},
                  'hun': {'common': 'Brazília',
                          'official': 'Brazil Szövetségi Köztársaság'},
                  'ita': {'common': 'Brasile',
                          'official': 'Repubblica federativa del Brasile'},
                  'jpn': {'common': 'ブラジル', 'official': 'ブラジル連邦共和国'},
                  'kor': {'common': '브라질', 'official': '브라질 연방 공화국'},
                  'nld': {'common': 'Brazilië',
                          'official': 'Federale Republiek Brazilië'},
                  'per': {'common': 'برزیل',
                          'official': 'جمهوری فدراتیو برزیل'},
                  'pol': {'common': 'Brazylia',
                          'official': 'Federacyjna Republika Brazylii'},
                  'por': {'common': 'Brasil',
                          'official': 'República Federativa do Brasil'},
                  'rus': {'common': 'Бразилия',
                          'official': 'Федеративная Республика Бразилия'},
                  'slk': {'common': 'Brazília',
                          'official': 'Brazílska federatívna republika'},
                  'spa': {'common': 'Brasil',
                          'official': 'República Federativa del Brasil'},
                  'srp': {'common': 'Бразил',
                          'official': 'Савезна Република Бразил'},
                  'swe': {'common': 'Brasilien',
                          'official': 'Förbundsrepubliken Brasilien'},
                  'tur': {'common': 'Brezilya',
                          'official': 'Brezilya Federal Cumhuriyeti'},
                  'urd': {'common': 'برازیل',
                          'official': 'وفاقی جمہوریہ برازیل'},
                  'zho': {'common': '巴西', 'official': '巴西联邦共和国'}},
 'unMember': True}

## Endpoint name

In [ ]:
URL_BRASIL = "https://restcountries.com/v3.1/name/brasil"

resposta_brasil = requests.get(URL_BRASIL).json()
resposta_brasil

[{'name': {'common': 'Brazil',
   'official': 'Federative Republic of Brazil',
   'nativeName': {'por': {'official': 'República Federativa do Brasil',
     'common': 'Brasil'}}},
  'tld': ['.br'],
  'cca2': 'BR',
  'ccn3': '076',
  'cca3': 'BRA',
  'cioc': 'BRA',
  'independent': True,
  'status': 'officially-assigned',
  'unMember': True,
  'currencies': {'BRL': {'name': 'Brazilian real', 'symbol': 'R$'}},
  'idd': {'root': '+5', 'suffixes': ['5']},
  'capital': ['Brasília'],
  'altSpellings': ['BR',
   'Brasil',
   'Federative Republic of Brazil',
   'República Federativa do Brasil'],
  'region': 'Americas',
  'subregion': 'South America',
  'languages': {'por': 'Portuguese'},
  'translations': {'ara': {'official': 'جمهورية البرازيل الاتحادية',
    'common': 'البرازيل'},
   'bre': {'official': 'Republik Kevreel Brazil', 'common': 'Brazil'},
   'ces': {'official': 'Brazilská federativní republika',
    'common': 'Brazílie'},
   'cym': {'official': 'Gweriniaeth Ffederal Brasil', 'common': 'Brasil'},
   'deu': {'official': 'Föderative Republik Brasilien', 'common': 'Brasilien'},
   'est': {'official': 'Brasiilia Liitvabariik', 'common': 'Brasiilia'},
   'fin': {'official': 'Brasilian liittotasavalta', 'common': 'Brasilia'},
   'fra': {'official': 'République fédérative du Brésil', 'common': 'Brésil'},
   'hrv': {'official': 'Savezne Republike Brazil', 'common': 'Brazil'},
   'hun': {'official': 'Brazil Szövetségi Köztársaság', 'common': 'Brazília'},
   'ita': {'official': 'Repubblica federativa del Brasile',
    'common': 'Brasile'},
   'jpn': {'official': 'ブラジル連邦共和国', 'common': 'ブラジル'},
   'kor': {'official': '브라질 연방 공화국', 'common': '브라질'},
   'nld': {'official': 'Federale Republiek Brazilië', 'common': 'Brazilië'},
   'per': {'official': 'جمهوری فدراتیو برزیل', 'common': 'برزیل'},
   'pol': {'official': 'Federacyjna Republika Brazylii', 'common': 'Brazylia'},
   'por': {'official': 'República Federativa do Brasil', 'common': 'Brasil'},
   'rus': {'official': 'Федеративная Республика Бразилия',
    'common': 'Бразилия'},
   'slk': {'official': 'Brazílska federatívna republika',
    'common': 'Brazília'},
   'spa': {'official': 'República Federativa del Brasil', 'common': 'Brasil'},
   'srp': {'official': 'Савезна Република Бразил', 'common': 'Бразил'},
   'swe': {'official': 'Förbundsrepubliken Brasilien', 'common': 'Brasilien'},
   'tur': {'official': 'Brezilya Federal Cumhuriyeti', 'common': 'Brezilya'},
   'urd': {'official': 'وفاقی جمہوریہ برازیل', 'common': 'برازیل'},
   'zho': {'official': '巴西联邦共和国', 'common': '巴西'}},
  'latlng': [-10.0, -55.0],
  'landlocked': False,
  'borders': ['ARG',
   'BOL',
   'COL',
   'GUF',
   'GUY',
   'PRY',
   'PER',
   'SUR',
   'URY',
   'VEN'],
  'area': 8515767.0,
  'demonyms': {'eng': {'f': 'Brazilian', 'm': 'Brazilian'},
   'fra': {'f': 'Brésilienne', 'm': 'Brésilien'}},
  'flag': '🇧🇷',
  'maps': {'googleMaps': 'https://goo.gl/maps/waCKk21HeeqFzkNC9',
   'openStreetMaps': 'https://www.openstreetmap.org/relation/59470'},
  'population': 212559409,
  'gini': {'2019': 53.4},
  'fifa': 'BRA',
  'car': {'signs': ['BR'], 'side': 'right'},
  'timezones': ['UTC-05:00', 'UTC-04:00', 'UTC-03:00', 'UTC-02:00'],
  'continents': ['South America'],
  'flags': {'png': 'https://flagcdn.com/w320/br.png',
   'svg': 'https://flagcdn.com/br.svg',
   'alt': "The flag of Brazil has a green field with a large yellow rhombus in the center. Within the rhombus is a dark blue globe with twenty-seven small five-pointed white stars depicting a starry sky and a thin white convex horizontal band inscribed with the national motto 'Ordem e Progresso' across its center."},
  'coatOfArms': {'png': 'https://mainfacts.com/media/images/coats_of_arms/br.png',
   'svg': 'https://mainfacts.com/media/images/coats_of_arms/br.svg'},
  'startOfWeek': 'monday',
  'capitalInfo': {'latlng': [-15.79, -47.88]},
  'postalCode': {'format': '#####-###', 'regex': '^(\\d{8})$'}}]

In [ ]:
pprint(resposta_brasil)

[{'altSpellings': ['BR',
                   'Brasil',
                   'Federative Republic of Brazil',
                   'República Federativa do Brasil'],
  'area': 8515767.0,
  'borders': ['ARG',
              'BOL',
              'COL',
              'GUF',
              'GUY',
              'PRY',
              'PER',
              'SUR',
              'URY',
              'VEN'],
  'capital': ['Brasília'],
  'capitalInfo': {'latlng': [-15.79, -47.88]},
  'car': {'side': 'right', 'signs': ['BR']},
  'cca2': 'BR',
  'cca3': 'BRA',
  'ccn3': '076',
  'cioc': 'BRA',
  'coatOfArms': {'png': 'https://mainfacts.com/media/images/coats_of_arms/br.png',
                 'svg': 'https://mainfacts.com/media/images/coats_of_arms/br.svg'},
  'continents': ['South America'],
  'currencies': {'BRL': {'name': 'Brazilian real', 'symbol': 'R$'}},
  'demonyms': {'eng': {'f': 'Brazilian', 'm': 'Brazilian'},
               'fra': {'f': 'Brésilienne', 'm': 'Brésilien'}},
  'fifa': 'BRA',
  'flag': '🇧🇷',
  'flags': {'alt': 'The flag of Brazil has a green field with a large yellow '
                   'rhombus in the center. Within the rhombus is a dark blue '
                   'globe with twenty-seven small five-pointed white stars '
                   'depicting a starry sky and a thin white convex horizontal '
                   "band inscribed with the national motto 'Ordem e Progresso' "
                   'across its center.',
            'png': 'https://flagcdn.com/w320/br.png',
            'svg': 'https://flagcdn.com/br.svg'},
  'gini': {'2019': 53.4},
  'idd': {'root': '+5', 'suffixes': ['5']},
  'independent': True,
  'landlocked': False,
  'languages': {'por': 'Portuguese'},
  'latlng': [-10.0, -55.0],
  'maps': {'googleMaps': 'https://goo.gl/maps/waCKk21HeeqFzkNC9',
           'openStreetMaps': 'https://www.openstreetmap.org/relation/59470'},
  'name': {'common': 'Brazil',
           'nativeName': {'por': {'common': 'Brasil',
                                  'official': 'República Federativa do '
                                              'Brasil'}},
           'official': 'Federative Republic of Brazil'},
  'population': 212559409,
  'postalCode': {'format': '#####-###', 'regex': '^(\\d{8})$'},
  'region': 'Americas',
  'startOfWeek': 'monday',
  'status': 'officially-assigned',
  'subregion': 'South America',
  'timezones': ['UTC-05:00', 'UTC-04:00', 'UTC-03:00', 'UTC-02:00'],
  'tld': ['.br'],
  'translations': {'ara': {'common': 'البرازيل',
                           'official': 'جمهورية البرازيل الاتحادية'},
                   'bre': {'common': 'Brazil',
                           'official': 'Republik Kevreel Brazil'},
                   'ces': {'common': 'Brazílie',
                           'official': 'Brazilská federativní republika'},
                   'cym': {'common': 'Brasil',
                           'official': 'Gweriniaeth Ffederal Brasil'},
                   'deu': {'common': 'Brasilien',
                           'official': 'Föderative Republik Brasilien'},
                   'est': {'common': 'Brasiilia',
                           'official': 'Brasiilia Liitvabariik'},
                   'fin': {'common': 'Brasilia',
                           'official': 'Brasilian liittotasavalta'},
                   'fra': {'common': 'Brésil',
                           'official': 'République fédérative du Brésil'},
                   'hrv': {'common': 'Brazil',
                           'official': 'Savezne Republike Brazil'},
                   'hun': {'common': 'Brazília',
                           'official': 'Brazil Szövetségi Köztársaság'},
                   'ita': {'common': 'Brasile',
                           'official': 'Repubblica federativa del Brasile'},
                   'jpn': {'common': 'ブラジル', 'official': 'ブラジル連邦共和国'},
                   'kor': {'common': '브라질', 'official': '브라질 연방 공화국'},
                   'nld': {'common': 'Brazilië',
                           'official': 'Federale Republiek Brazilië'},
                   'per': {'common': 'برزیل',
                           'official': 'جمهوری فدراتیو برزیل'},
                   'pol': {'common': 'Brazylia',
                           'official': 'Federacyjna Republika Brazylii'},
                   'por': {'common': 'Brasil',
                           'official': 'República Federativa do Brasil'},
                   'rus': {'common': 'Бразилия',
                           'official': 'Федеративная Республика Бразилия'},
                   'slk': {'common': 'Brazília',
                           'official': 'Brazílska federatívna republika'},
                   'spa': {'common': 'Brasil',
                           'official': 'República Federativa del Brasil'},
                   'srp': {'common': 'Бразил',
                           'official': 'Савезна Република Бразил'},
                   'swe': {'common': 'Brasilien',
                           'official': 'Förbundsrepubliken Brasilien'},
                   'tur': {'common': 'Brezilya',
                           'official': 'Brezilya Federal Cumhuriyeti'},
                   'urd': {'common': 'برازیل',
                           'official': 'وفاقی جمہوریہ برازیل'},
                   'zho': {'common': '巴西', 'official': '巴西联邦共和国'}},
  'unMember': True}]

In [ ]:
resposta_brasil[0].keys()

dict_keys(['name', 'tld', 'cca2', 'ccn3', 'cca3', 'cioc', 'independent', 'status', 'unMember', 'currencies', 'idd', 'capital', 'altSpellings', 'region', 'subregion', 'languages', 'translations', 'latlng', 'landlocked', 'borders', 'area', 'demonyms', 'flag', 'maps', 'population', 'gini', 'fifa', 'car', 'timezones', 'continents', 'flags', 'coatOfArms', 'startOfWeek', 'capitalInfo', 'postalCode'])

## Endpoint region

In [ ]:
# pegando todos os países da América do Sul, com seus nomes, população e capitais
URL_AMERICA_SUL_FILTROS = "https://restcountries.com/v3.1/region/south%20america?fields=name,population,capital"
requests.get(URL_AMERICA_SUL_FILTROS).status_code

200

In [ ]:
resposta_america_sul = requests.get(URL_AMERICA_SUL_FILTROS).json()
resposta_america_sul[:5]

[{'name': {'common': 'Brazil',
   'official': 'Federative Republic of Brazil',
   'nativeName': {'por': {'official': 'República Federativa do Brasil',
     'common': 'Brasil'}}},
  'capital': ['Brasília'],
  'population': 212559409},
 {'name': {'common': 'Venezuela',
   'official': 'Bolivarian Republic of Venezuela',
   'nativeName': {'spa': {'official': 'República Bolivariana de Venezuela',
     'common': 'Venezuela'}}},
  'capital': ['Caracas'],
  'population': 28435943},
 {'name': {'common': 'Peru',
   'official': 'Republic of Peru',
   'nativeName': {'aym': {'official': 'Piruw Suyu', 'common': 'Piruw'},
    'que': {'official': 'Piruw Ripuwlika', 'common': 'Piruw'},
    'spa': {'official': 'República del Perú', 'common': 'Perú'}}},
  'capital': ['Lima'],
  'population': 32971846},
 {'name': {'common': 'Guyana',
   'official': 'Co-operative Republic of Guyana',
   'nativeName': {'eng': {'official': 'Co-operative Republic of Guyana',
     'common': 'Guyana'}}},
  'capital': ['Georgetown'],
  'population': 786559},
 {'name': {'common': 'Ecuador',
   'official': 'Republic of Ecuador',
   'nativeName': {'spa': {'official': 'República del Ecuador',
     'common': 'Ecuador'}}},
  'capital': ['Quito'],
  'population': 17643060}]

In [ ]:
# organizando os dados que queremos (nome comum, população e capital)
paises_america_sul = []
for pais in resposta_america_sul:
    novo_pais = {
        'nome': pais['name']['common'],
        'populacao': pais['population'],
        'capital': pais['capital'][0]
    }
    paises_america_sul.append(novo_pais)

paises_america_sul[:5]

[{'nome': 'Brazil', 'populacao': 212559409, 'capital': 'Brasília'},
 {'nome': 'Venezuela', 'populacao': 28435943, 'capital': 'Caracas'},
 {'nome': 'Peru', 'populacao': 32971846, 'capital': 'Lima'},
 {'nome': 'Guyana', 'populacao': 786559, 'capital': 'Georgetown'},
 {'nome': 'Ecuador', 'populacao': 17643060, 'capital': 'Quito'}]

In [ ]:
# convertendo a resposta para um DataFrame
import pandas as pd

df = pd.DataFrame(paises_america_sul)
df.head()

        nome  populacao     capital
0     Brazil  212559409    Brasília
1  Venezuela   28435943     Caracas
2       Peru   32971846        Lima
3     Guyana     786559  Georgetown
4    Ecuador   17643060       Quito

In [ ]:
df.tail()

                nome  populacao     capital
9      French Guiana     254541     Cayenne
10           Bolivia   11673029       Sucre
11           Uruguay    3473727  Montevideo
12  Falkland Islands       2563     Stanley
13             Chile   19116209    Santiago

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   nome       14 non-null     object
 1   populacao  14 non-null     int64
 2   capital    14 non-null     object
dtypes: int64(1), object(2)
memory usage: 468.0+ bytes