# Consumindo APIs que precisam de keys

Fonte: https://fred.stlouisfed.org/

Agora, precisamos de uma key para consumir a API. Para isso, é necessário criar uma conta no site e gerar uma key. A key é um código que identifica o usuário e permite o acesso à API. Este é um cenário muito comum, pois muitas APIs são pagas e precisam de uma key para serem consumidas. Neste caso, a API é gratuita e a key é gerada automaticamente.

>  "This product uses the FRED® API but is not endorsed or certified by the Federal Reserve Bank of St. Louis."

## Usando variáveis de ambiente para armazenar a key

Um problema comum é que, ao compartilhar o código, a key fica exposta. Uma solução é armazenar a key em uma variável de ambiente. Variáveis de ambiente são variáveis que ficam armazenadas no sistema operacional e podem ser acessadas por qualquer programa.

Para não expor a key no código, vamos armazená-la em uma variável de ambiente. Para isso, vamos usar a biblioteca `python-dotenv`. Para instalar, basta rodar o comando abaixo no terminal:

```bash
pip install python-dotenv
```

Agora, vamos criar um arquivo `.env` na raiz do projeto e adicionar a key da API:

```bash
FRED_API_KEY=1234567890
```

Para ler a variável de ambiente, vamos usar a biblioteca `os`:

```python
from dotenv import load_dotenv
import os

load_dotenv()

key = os.getenv("FRED_API_KEY")
```

In [1]:
from dotenv import load_dotenv
import os

load_dotenv()

key = os.getenv("FRED_API_KEY")

# key  # apenas verificando. NUNCA imprima a key no código

## Endpoint series/search

In [2]:
BUSCA_BR = "brazil"

URL_BRASIL_BUSCA = f"https://api.stlouisfed.org/fred/series/search?search_text={BUSCA_BR}&api_key={key}&file_type=json"

In [3]:
import requests

resposta_br_busca = requests.get(URL_BRASIL_BUSCA)

resposta_br_busca.status_code

200

In [4]:
resposta_br_busca.headers

{'Content-Type': 'application/json; charset=UTF-8', 'Expires': 'Thu, 10 Aug 2023 19:22:10 GMT', 'x-rate-limit-limit': '120', 'x-rate-limit-remaining': '120', 'Vary': 'Accept-Encoding', 'ETag': 'W/"11c1bd095ca94f4b779bfe99ff8d1282-gzip-gzip"', 'Content-Encoding': 'gzip', 'Accept-Ranges': 'bytes', 'Content-Length': '82534', 'Date': 'Thu, 10 Aug 2023 19:12:11 GMT', 'Connection': 'keep-alive'}

In [5]:
# resposta_br_busca.json()

In [6]:
type(resposta_br_busca.json())

dict

In [7]:
resposta_br_busca.json()["seriess"][0]

{'id': 'CPALTT01BRM659N',
 'realtime_start': '2023-08-10',
 'realtime_end': '2023-08-10',
 'title': 'Consumer Price Index: All Items: Total: Total for Brazil',
 'observation_start': '1980-12-01',
 'observation_end': '2023-05-01',
 'frequency': 'Monthly',
 'frequency_short': 'M',
 'units': 'Growth rate same period previous year',
 'units_short': 'Growth rate same period previous Yr.',
 'seasonal_adjustment': 'Not Seasonally Adjusted',
 'seasonal_adjustment_short': 'NSA',
 'last_updated': '2023-08-09 10:23:07-05',
 'popularity': 30,
 'group_popularity': 47,
 'notes': 'OECD descriptor ID: CPALTT01\nOECD unit ID: GY\nOECD country ID: BRA\n\nAll OECD data should be cited as follows: OECD, "Main Economic Indicators - complete database", Main Economic Indicators (database),http://dx.doi.org/10.1787/data-00052-en (Accessed on date)\nCopyright, 2016, OECD. Reprinted with permission.'}

### Paginação

In [8]:
# limitando a 5 resultados
LIMIT = 5

URL_BRASIL_BUSCA_5 = f"https://api.stlouisfed.org/fred/series/search?search_text={BUSCA_BR}&api_key={key}&file_type=json&limit={LIMIT}"

requests.get(URL_BRASIL_BUSCA_5).json()

{'realtime_start': '2023-08-10',
 'realtime_end': '2023-08-10',
 'order_by': 'search_rank',
 'sort_order': 'desc',
 'count': 1198,
 'offset': 0,
 'limit': 5,
 'seriess': [{'id': 'CPALTT01BRM659N',
   'realtime_start': '2023-08-10',
   'realtime_end': '2023-08-10',
   'title': 'Consumer Price Index: All Items: Total: Total for Brazil',
   'observation_start': '1980-12-01',
   'observation_end': '2023-05-01',
   'frequency': 'Monthly',
   'frequency_short': 'M',
   'units': 'Growth rate same period previous year',
   'units_short': 'Growth rate same period previous Yr.',
   'seasonal_adjustment': 'Not Seasonally Adjusted',
   'seasonal_adjustment_short': 'NSA',
   'last_updated': '2023-08-09 10:23:07-05',
   'popularity': 30,
   'group_popularity': 47,
   'notes': 'OECD descriptor ID: CPALTT01\nOECD unit ID: GY\nOECD country ID: BRA\n\nAll OECD data should be cited as follows: OECD, "Main Economic Indicators - complete database", Main Economic Indicators (database),http://dx.doi.org/10.1787/data-00052-en (Accessed on date)\nCopyright, 2016, OECD. Reprinted with permission.'},
  {'id': 'BRACPIALLMINMEI',
   'realtime_start': '2023-08-10',
   'realtime_end': '2023-08-10',
   'title': 'Consumer Price Index: All Items: Total: Total for Brazil',
   'observation_start': '1979-12-01',
   'observation_end': '2023-05-01',
   'frequency': 'Monthly',
   'frequency_short': 'M',
   'units': 'Index 2015=100',
   'units_short': 'Index 2015=100',
   'seasonal_adjustment': 'Not Seasonally Adjusted',
   'seasonal_adjustment_short': 'NSA',
   'last_updated': '2023-08-09 10:23:08-05',
   'popularity': 29,
   'group_popularity': 47,
   'notes': 'Copyright, 2016, OECD. Reprinted with permission.\n\nAll OECD data should be cited as follows: OECD (2010), "Main Economic Indicators - complete database", Main Economic Indicators (database),http://dx.doi.org/10.1787/data-00052-en (Accessed on date)'},
  {'id': 'CPALTT01BRM657N',
   'realtime_start': '2023-08-10',
   'realtime_end': '2023-08-10',
   'title': 'Consumer Price Index: All Items: Total: Total for Brazil',
   'observation_start': '1980-01-01',
   'observation_end': '2023-05-01',
   'frequency': 'Monthly',
   'frequency_short': 'M',
   'units': 'Growth rate previous period',
   'units_short': 'Growth rate previous period',
   'seasonal_adjustment': 'Not Seasonally Adjusted',
   'seasonal_adjustment_short': 'NSA',
   'last_updated': '2023-08-09 10:23:09-05',
   'popularity': 11,
   'group_popularity': 47,
   'notes': 'OECD descriptor ID: CPALTT01\nOECD unit ID: GP\nOECD country ID: BRA\n\nAll OECD data should be cited as follows: OECD, "Main Economic Indicators - complete database", Main Economic Indicators (database),http://dx.doi.org/10.1787/data-00052-en (Accessed on date)\nCopyright, 2016, OECD. Reprinted with permission.'},
  {'id': 'BRACPIALLAINMEI',
   'realtime_start': '2023-08-10',
   'realtime_end': '2023-08-10',
   'title': 'Consumer Price Index: All Items: Total: Total for Brazil',
   'observation_start': '1980-01-01',
   'observation_end': '2022-01-01',
   'frequency': 'Annual',
   'frequency_short': 'A',
   'units': 'Index 2015=100',
   'units_short': 'Index 2015=100',
   'seasonal_adjustment': 'Not Seasonally Adjusted',
   'seasonal_adjustment_short': 'NSA',
   'last_updated': '2023-02-14 11:48:02-06',
   'popularity': 10,
   'group_popularity': 47,
   'notes': 'Copyright, 2016, OECD. Reprinted with permission.\n\nAll OECD data should be cited as follows: OECD (2010), "Main Economic Indicators - complete database", Main Economic Indicators (database),http://dx.doi.org/10.1787/data-00052-en (Accessed on date)'},
  {'id': 'BRACPALTT01IXNBM',
   'realtime_start': '2023-08-10',
   'realtime_end': '2023-08-10',
   'title': 'Consumer Price Index: All items: Total: Total for Brazil',
   'observation_start': '1979-12-01',
   'observation_end': '2023-05-01',
   'frequency': 'Monthly',
   'frequency_short': 'M',
   'units': 'Index source base',
   'units_short': 'Index source base',
   'seasonal_adjustment': 'Not Seasonally Adjusted',
   'seasonal_adjustment_short': 'NSA',
   'last_updated': '2023-08-09 10:23:10-05',
   'popularity': 6,
   'group_popularity': 47,
   'notes': 'OECD descriptor ID: CPALTT01 OECD unit ID: IXNB OECD country ID: BRA All OECD data should be cited as follows: OECD,"Main Economic Indicators - complete database"Main Economic Indicators(database)http://dx.doi.org/10.1787/data-00052-en(Accessed on date)Copyright, 2016, OECD. Reprinted with permission.'}]}

In [9]:
# limitando a 5 resultados, mas com offset
LIMIT = 5
OFFSET = 5

URL_BRASIL_BUSCA_5_OFFSET = f"https://api.stlouisfed.org/fred/series/search?search_text={BUSCA_BR}&api_key={key}&file_type=json&limit={LIMIT}&offset={OFFSET}"

requests.get(URL_BRASIL_BUSCA_5_OFFSET).json()

{'realtime_start': '2023-08-10',
 'realtime_end': '2023-08-10',
 'order_by': 'search_rank',
 'sort_order': 'desc',
 'count': 1198,
 'offset': 5,
 'limit': 5,
 'seriess': [{'id': 'CPALTT01BRQ657N',
   'realtime_start': '2023-08-10',
   'realtime_end': '2023-08-10',
   'title': 'Consumer Price Index: All Items: Total: Total for Brazil',
   'observation_start': '1980-04-01',
   'observation_end': '2023-01-01',
   'frequency': 'Quarterly',
   'frequency_short': 'Q',
   'units': 'Growth rate previous period',
   'units_short': 'Growth rate previous period',
   'seasonal_adjustment': 'Not Seasonally Adjusted',
   'seasonal_adjustment_short': 'NSA',
   'last_updated': '2023-05-10 14:21:06-05',
   'popularity': 4,
   'group_popularity': 47,
   'notes': 'OECD descriptor ID: CPALTT01\nOECD unit ID: GP\nOECD country ID: BRA\n\nAll OECD data should be cited as follows: OECD, "Main Economic Indicators - complete database", Main Economic Indicators (database),http://dx.doi.org/10.1787/data-00052-en (Accessed on date)\nCopyright, 2016, OECD. Reprinted with permission.'},
  {'id': 'CPALTT01BRQ659N',
   'realtime_start': '2023-08-10',
   'realtime_end': '2023-08-10',
   'title': 'Consumer Price Index: All Items: Total: Total for Brazil',
   'observation_start': '1981-01-01',
   'observation_end': '2023-01-01',
   'frequency': 'Quarterly',
   'frequency_short': 'Q',
   'units': 'Growth rate same period previous year',
   'units_short': 'Growth rate same period previous Yr.',
   'seasonal_adjustment': 'Not Seasonally Adjusted',
   'seasonal_adjustment_short': 'NSA',
   'last_updated': '2023-05-10 14:21:06-05',
   'popularity': 2,
   'group_popularity': 47,
   'notes': 'OECD descriptor ID: CPALTT01\nOECD unit ID: GY\nOECD country ID: BRA\n\nAll OECD data should be cited as follows: OECD, "Main Economic Indicators - complete database", Main Economic Indicators (database),http://dx.doi.org/10.1787/data-00052-en (Accessed on date)\nCopyright, 2016, OECD. Reprinted with permission.'},
  {'id': 'BRACPIALLQINMEI',
   'realtime_start': '2023-08-10',
   'realtime_end': '2023-08-10',
   'title': 'Consumer Price Index: All Items: Total: Total for Brazil',
   'observation_start': '1980-01-01',
   'observation_end': '2023-01-01',
   'frequency': 'Quarterly',
   'frequency_short': 'Q',
   'units': 'Index 2015=100',
   'units_short': 'Index 2015=100',
   'seasonal_adjustment': 'Not Seasonally Adjusted',
   'seasonal_adjustment_short': 'NSA',
   'last_updated': '2023-05-10 14:21:04-05',
   'popularity': 2,
   'group_popularity': 47,
   'notes': 'Copyright, 2016, OECD. Reprinted with permission.\n\nAll OECD data should be cited as follows: OECD (2010), "Main Economic Indicators - complete database", Main Economic Indicators (database),http://dx.doi.org/10.1787/data-00052-en (Accessed on date)'},
  {'id': 'BRACPALTT01IXNBQ',
   'realtime_start': '2023-08-10',
   'realtime_end': '2023-08-10',
   'title': 'Consumer Price Index: All items: Total: Total for Brazil',
   'observation_start': '1980-01-01',
   'observation_end': '2023-01-01',
   'frequency': 'Quarterly',
   'frequency_short': 'Q',
   'units': 'Index source base',
   'units_short': 'Index source base',
   'seasonal_adjustment': 'Not Seasonally Adjusted',
   'seasonal_adjustment_short': 'NSA',
   'last_updated': '2023-05-10 14:21:14-05',
   'popularity': 2,
   'group_popularity': 47,
   'notes': 'OECD descriptor ID: CPALTT01 OECD unit ID: IXNB OECD country ID: BRA All OECD data should be cited as follows: OECD,"Main Economic Indicators - complete database"Main Economic Indicators(database)http://dx.doi.org/10.1787/data-00052-en(Accessed on date)Copyright, 2016, OECD. Reprinted with permission.'},
  {'id': 'CPALTT01BRA657N',
   'realtime_start': '2023-08-10',
   'realtime_end': '2023-08-10',
   'title': 'Consumer Price Index: All Items: Total: Total for Brazil',
   'observation_start': '1981-01-01',
   'observation_end': '2022-01-01',
   'frequency': 'Annual',
   'frequency_short': 'A',
   'units': 'Growth rate previous period',
   'units_short': 'Growth rate previous period',
   'seasonal_adjustment': 'Not Seasonally Adjusted',
   'seasonal_adjustment_short': 'NSA',
   'last_updated': '2023-02-14 12:02:36-06',
   'popularity': 1,
   'group_popularity': 47,
   'notes': 'OECD descriptor ID: CPALTT01\nOECD unit ID: GP\nOECD country ID: BRA\n\nAll OECD data should be cited as follows: OECD, "Main Economic Indicators - complete database", Main Economic Indicators (database),http://dx.doi.org/10.1787/data-00052-en (Accessed on date)\nCopyright, 2016, OECD. Reprinted with permission.'}]}

### Passando para um dataframe

In [10]:
# voltando a usar o limite padrão (1000)
import pandas as pd

df_busca = pd.DataFrame(resposta_br_busca.json()["seriess"])
df_busca.head()

,id,realtime_start,realtime_end,title,observation_start,observation_end,frequency,frequency_short,units,units_short,seasonal_adjustment,seasonal_adjustment_short,last_updated,popularity,group_popularity,notes
0,CPALTT01BRM659N,2023-08-10,2023-08-10,Consumer Price Index: All Items: Total: Total ...,1980-12-01,2023-05-01,Monthly,M,Growth rate same period previous year,Growth rate same period previous Yr.,Not Seasonally Adjusted,NSA,2023-08-09 10:23:07-05,30,47,OECD descriptor ID: CPALTT01\nOECD unit ID: GY...
1,BRACPIALLMINMEI,2023-08-10,2023-08-10,Consumer Price Index: All Items: Total: Total ...,1979-12-01,2023-05-01,Monthly,M,Index 2015=100,Index 2015=100,Not Seasonally Adjusted,NSA,2023-08-09 10:23:08-05,29,47,"Copyright, 2016, OECD. Reprinted with permissi..."
2,CPALTT01BRM657N,2023-08-10,2023-08-10,Consumer Price Index: All Items: Total: Total ...,1980-01-01,2023-05-01,Monthly,M,Growth rate previous period,Growth rate previous period,Not Seasonally Adjusted,NSA,2023-08-09 10:23:09-05,11,47,OECD descriptor ID: CPALTT01\nOECD unit ID: GP...
3,BRACPIALLAINMEI,2023-08-10,2023-08-10,Consumer Price Index: All Items: Total: Total ...,1980-01-01,2022-01-01,Annual,A,Index 2015=100,Index 2015=100,Not Seasonally Adjusted,NSA,2023-02-14 11:48:02-06,10,47,"Copyright, 2016, OECD. Reprinted with permissi..."
4,BRACPALTT01IXNBM,2023-08-10,2023-08-10,Consumer Price Index: All items: Total: Total ...,1979-12-01,2023-05-01,Monthly,M,Index source base,Index source base,Not Seasonally Adjusted,NSA,2023-08-09 10:23:10-05,6,47,OECD descriptor ID: CPALTT01 OECD unit ID: IXN...

In [11]:
df_busca.tail()

,id,realtime_start,realtime_end,title,observation_start,observation_end,frequency,frequency_short,units,units_short,seasonal_adjustment,seasonal_adjustment_short,last_updated,popularity,group_popularity,notes
995,MABMBM01BRA659S,2023-08-10,2023-08-10,"Broad Money, Index for Brazil (DISCONTINUED)",1997-01-01,2013-01-01,Annual,A,Growth Rate Same Period Previous Year,Growth Rate Same Period Previous Yr.,Not Seasonally Adjusted,NSA,2014-03-12 10:54:18-05,0,1,OECD descriptor ID: MABMBM01\nOECD unit ID: GY...
996,MABMBM01BRA661S,2023-08-10,2023-08-10,"Broad Money, Index for Brazil (DISCONTINUED)",1996-01-01,2013-01-01,Annual,A,Index 2010=1,Index 2010=1,Not Seasonally Adjusted,NSA,2014-03-12 10:54:18-05,0,1,OECD descriptor ID: MABMBM01\nOECD unit ID: IX...
997,MABMBM01BRM657S,2023-08-10,2023-08-10,"Broad Money, Index for Brazil (DISCONTINUED)",1995-03-01,2013-12-01,Monthly,M,Growth Rate Previous Period,Growth Rate Previous Period,Seasonally Adjusted,SA,2014-03-12 10:54:18-05,0,1,OECD descriptor ID: MABMBM01\nOECD unit ID: GP...
998,MABMBM01BRM659S,2023-08-10,2023-08-10,"Broad Money, Index for Brazil (DISCONTINUED)",1996-02-01,2013-12-01,Monthly,M,Growth Rate Same Period Previous Year,Growth Rate Same Period Previous Yr.,Seasonally Adjusted,SA,2014-03-12 10:54:18-05,0,1,OECD descriptor ID: MABMBM01\nOECD unit ID: GY...
999,MABMBM01BRM661S,2023-08-10,2023-08-10,"Broad Money, Index for Brazil (DISCONTINUED)",1995-02-01,2013-12-01,Monthly,M,Index 2010=1,Index 2010=1,Seasonally Adjusted,SA,2014-03-12 10:54:18-05,0,1,OECD descriptor ID: MABMBM01\nOECD unit ID: IX...

In [12]:
# procurando por "dollar" no nome da série
df_busca[df_busca["title"].str.contains("dollar", case=False)]

,id,realtime_start,realtime_end,title,observation_start,observation_end,frequency,frequency_short,units,units_short,seasonal_adjustment,seasonal_adjustment_short,last_updated,popularity,group_popularity,notes
14,DEXBZUS,2023-08-10,2023-08-10,Brazilian Reals to U.S. Dollar Spot Exchange Rate,1995-01-02,2023-08-04,Daily,D,Brazilian Reals to One U.S. Dollar,Brazilian Reals to 1 U.S. $,Not Seasonally Adjusted,NSA,2023-08-07 15:25:02-05,46,50,Noon buying rates in New York City for cable t...
16,EXBZUS,2023-08-10,2023-08-10,Brazilian Reals to U.S. Dollar Spot Exchange Rate,1995-01-01,2023-07-01,Monthly,M,Brazilian Reals to One U.S. Dollar,Brazilian Reals to 1 U.S. $,Not Seasonally Adjusted,NSA,2023-08-07 15:21:05-05,28,50,Averages of daily figures. Noon buying rates i...
17,AEXBZUS,2023-08-10,2023-08-10,Brazilian Reals to U.S. Dollar Spot Exchange Rate,1995-01-01,2022-01-01,Annual,A,Brazilian Reals to One U.S. Dollar,Brazilian Reals to 1 U.S. $,Not Seasonally Adjusted,NSA,2023-01-03 16:56:04-06,5,50,Averages of daily figures. Noon buying rates i...
260,FXRATEBRA618NUPN,2023-08-10,2023-08-10,Exchange Rate to U.S. Dollar for Brazil,1950-01-01,2010-01-01,Annual,A,National Currency Units per US Dollar,National Currency Units per US $,Not Seasonally Adjusted,NSA,2012-09-17 12:02:54-05,2,2,For more information and proper citation see h...

In [13]:
SERIE_DOLLAR = "DEXBZUS"

URL_SERIE_DOLLAR = f"https://api.stlouisfed.org/fred/series/observations?series_id={SERIE_DOLLAR}&api_key={key}&file_type=json"

In [14]:
resposta_dollar = requests.get(URL_SERIE_DOLLAR)

resposta_dollar.status_code

200

In [15]:
# resposta_dollar.json()

In [16]:
df_dollar = pd.DataFrame(resposta_dollar.json()["observations"])
df_dollar.head()

  realtime_start realtime_end        date   value
0     2023-08-10   2023-08-10  1995-01-02  0.8440
1     2023-08-10   2023-08-10  1995-01-03  0.8450
2     2023-08-10   2023-08-10  1995-01-04  0.8450
3     2023-08-10   2023-08-10  1995-01-05  0.8430
4     2023-08-10   2023-08-10  1995-01-06  0.8400

In [17]:
df_dollar.tail()

     realtime_start realtime_end        date   value
7455     2023-08-10   2023-08-10  2023-07-31  4.7407
7456     2023-08-10   2023-08-10  2023-08-01  4.7824
7457     2023-08-10   2023-08-10  2023-08-02   4.814
7458     2023-08-10   2023-08-10  2023-08-03   4.882
7459     2023-08-10   2023-08-10  2023-08-04  4.8548

In [18]:
df_dollar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7460 entries, 0 to 7459
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   realtime_start  7460 non-null   object
 1   realtime_end    7460 non-null   object
 2   date            7460 non-null   object
 3   value           7460 non-null   object
dtypes: object(4)
memory usage: 233.3+ KB